### ISSUE TITLE
PHPConsole intermittently not working. JS errors in extension console.

### ISSUE THREAD

**Issue by digitaloutback** [barbushin/php-console#142]
`Error in response to tabs.get: TypeError: Cannot read property 'status' of undefined
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:114)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83
13:07:14.643 background.html:1 Unchecked runtime.lastError while running tabs.get: No tab with id: 779.
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83
13:07:14.644 background.html:1 Error in response to tabs.get: TypeError: Cannot read property 'status' of undefined
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:114)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83
13:07:14.645 background.html:1 Unchecked runtime.lastError while running tabs.get: No tab with id: 779.
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83
13:07:14.743 background.html:1 Error in response to tabs.get: TypeError: Cannot read property 'status' of undefined
    at Object.callback (chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:114)
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83
13:07:14.744 background.html:1 Unchecked runtime.lastError while running tabs.get: No tab with id: 779.
    at chrome-extension://nfhmhhlpfleoednkpnnnkolmclajemef/background.js:21:83`

**Comment by Chematronix** [comment]
Can confirm.  Over a 100 errors per second:

![image](https://user-images.githubusercontent.com/6773039/60688483-5453a280-9e6a-11e9-8c07-c7d5a42eb2fd.png)

**Comment by barbushin** [comment]
@Chematronix just released fixed 3.0.40 version, it will be published in next few hours. Please let me know if this error will persist after update.
